# Audio with numpy unsolved

### Basic of numpy and music

numpy is a python library for **veector** (also higher-dimensional analos: matrix, tensor) computatinos modelled after matlab.

we will use numpy.array's which work similarly to lists (len, indexing etc), but they really behave like mathematical vectors in terms of (*, +)

we'll also look at:
* np.pi
* adding an np.array by a scalar, multiplying by another vector
* np.concatenate
* np.linspace, np.zeros, np.ones
* np.sin, np.cos, np.sqrt, np.log...
* np.max, np.min



#### an applicaton
represnt data as vectors

try to **compose music**

### Importing numpy and accessing its contents

In [ ]:
import numpy as np # we import the numpy package and give it an alias (name)

In [3]:
np.pi, np.cos(0)

(3.141592653589793, np.float64(1.0))

### Basics of np.arrays

> We'll often use them for mathematical vectors. Below $u,v \in \mathbb{R}^4$.

Sometimes you will create np.arrays from lists/tuples

In [10]:
u = np.array([1., 2, 3, 10]) # if you want floats, >= element should be a float!
v = np.array([100.0, 200, 300, 500])

print(u)
print(v)
print(u+v) # let's try some more! what does u*v do? what else can we do?
print(u*v)

[ 1.  2.  3. 10.]
[100. 200. 300. 500.]
[101. 202. 303. 510.]
[ 100.  400.  900. 5000.]


In [16]:
v.dtype

# data types (dtype):
# numpy arrays are homogenous, meaning every element in the array must be the same type. 
# v.dtype returned float 64. this happened because even one decimal point (like 100.0)
# tells numpy to treat the whole array as floating point numvers for precision.


dtype('float64')

In [12]:
u

array([ 1.,  2.,  3., 10.])

In [13]:
v*u + 3*v - u - v

array([ 299.,  798., 1497., 5990.])

In [14]:
v*u

array([ 100.,  400.,  900., 5000.])

In [18]:
len(u)

4

In [21]:
u.shape

# shape tells you the dimensinoality of the array.
# the 5 means there are four elements in that directon.
# the comma with nothing after indicates this is a 1D array (a simple vector)

(4,)

In [22]:
u[0], u[-1], u[:2], u[-2:]

# u[0] : first element
# u[-1]: last element
# u[:2]: slice (start): grab everything up to (but not incldueing index 2)
# u[-2:] slice (end): grab everything from the second-to-last element to the end

(np.float64(1.0), np.float64(10.0), array([1., 2.]), array([ 3., 10.]))

In [24]:
u[:2] = 0 # we can also change a sub-arrray, useful!
u   # that means slice (start) to index 2 > zero!

array([ 0.,  0.,  3., 10.])

### Arrays of ones and zeros
it's often useful to have a large array of zeros or ones, so that you can do something to them.

In [25]:
np.ones(10), np.zeros(10)

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

#### np.linspace (super useful)

used to create n numbers evenly spaced between a and b (inclusive)
> it also works if a and b are np.arrays/vectors

In [26]:
xs = np.linspace(0, np.pi, 10**6)
print(xs, len(xs))

[0.00000000e+00 3.14159580e-06 6.28319159e-06 ... 3.14158637e+00
 3.14158951e+00 3.14159265e+00] 1000000


### Applying functions on np.arrays

If we apply a mathematical function $f : \mathbb{R} \to \mathbb{R}$ to a vector in $\mathbb{R}^n$, numpy will automatically compute $f$ on each component of this vector.

> As we'll see in a moment, this is *much* more efficient than doing a list comprehension!

In [27]:
values = np.sin(xs) # [sin(xs[0]), sin(xs[1]), ...]

In [28]:
len(values)

1000000

In [29]:
values

array([0.00000000e+00, 3.14159580e-06, 6.28319159e-06, ...,
       6.28319159e-06, 3.14159580e-06, 1.22464680e-16], shape=(1000000,))

### Summing etc

In [30]:
# np.sum(np.sin(xs))
np.sum(values)

np.float64(636619.1357472853)